/* Each new term in the Fibonacci sequence is generated by adding the previous two terms.
   By starting with 1 and 2, the first 10 terms will be:

   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

   By considering the terms in the Fibonacci sequence whose values do not exceed four million,
   find the sum of the even-valued terms
*/

public class Euler2
{
    public static void main(String[] args)
    {
        int sum = 0;
        int first = 0;
        int second = 1;

        while ((first + second) <= 4000000)
        {
            int third = first + second;

            if (third % 2 == 0 )
            {
                sum += third;
            }

            first = second;
            second = third;
        }

        System.out.println("The sum of all fibonacci numbers below 4 million is: " + sum);
    }
}
